import type { Product, Testimonial } from "./types";

// ─── Products (prices in COP) ───────────────────────────────────────
export const products: Product[] = [
  {
    slug: "kore-gelatina-10k",
    name: "Kore Gelatina 10K",
    tagline: "Gelatina de remolacha bioactivada para carreras de 10K",
    description:
      "Nuestra gelatina insignia en formato barra de 15g. Deliciosa gelatina de remolacha con nitratos bioactivados, diseñada para optimizar tu rendimiento en carreras de 10 kilómetros. Protocolo de 1 Carga + 2 Refuerzo para máximo aprovechamiento. Fácil de llevar, fácil de consumir, sabor increíble.",
    price: 12_900,
    originalPrice: 15_900,
    image: "/productos/gelatina-10k.jpg",
    badge: "Estrella",
    rating: 4.9,
    reviews: 1847,
    benefits: [
      "Mejora el flujo sanguíneo y la oxigenación muscular",
      "Reduce el consumo de oxígeno durante el ejercicio",
      "Protocolo 1 Carga + 2 Refuerzo para máximo rendimiento",
      "Formato barra de gelatina: práctico y delicioso",
    ],
    ingredients: [
      "Nitratos de remolacha bioactivados",
      "Gelatina natural",
      "Concentrado de remolacha",
      "Neto 15g por barra",
    ],
    category: "Gelatinas",
  },
  {
    slug: "kore-gelatina-21k",
    name: "Kore Gelatina 21K",
    tagline: "Concentración extra en gelatina para media maratón",
    description:
      "Gelatina de remolacha con doble concentración de nitratos bioactivados, formulada específicamente para esfuerzos de media maratón y distancias superiores. Mismo formato barra de 15g que amas, con el doble de potencia para cuando necesitas ir más lejos.",
    price: 18_900,
    image: "/productos/gelatina-21k.jpg",
    badge: "Pro",
    rating: 4.8,
    reviews: 389,
    benefits: [
      "Doble concentración de nitratos",
      "Efecto prolongado para distancias largas",
      "Vasodilatación sostenida por más tiempo",
      "Ideal para media maratón y trail",
    ],
    ingredients: [
      "Nitratos de remolacha bioactivados 2x",
      "Gelatina natural",
      "Concentrado de remolacha premium",
      "Neto 15g por barra",
    ],
    category: "Gelatinas",
  },
  {
    slug: "kore-jugo-natural",
    name: "Kore Jugo Natural",
    tagline: "Jugo 100% natural de remolacha prensada en frío",
    description:
      "Jugo natural de remolacha prensada en frío, sin aditivos ni conservantes. Cada botella contiene la concentración óptima de nitratos naturales para apoyar tu rendimiento deportivo diario y tu salud cardiovascular.",
    price: 16_900,
    image: "/productos/jugo-natural.jpg",
    badge: "Natural",
    rating: 4.8,
    reviews: 923,
    benefits: [
      "100% remolacha prensada en frío",
      "Alto contenido de nitratos naturales",
      "Apoya la salud cardiovascular diaria",
      "Sin conservantes ni aditivos artificiales",
    ],
    ingredients: [
      "Remolacha orgánica 100%",
      "Prensado en frío",
      "Sin azúcares añadidos",
      "Sin conservantes",
    ],
    category: "Jugos",
  },
  {
    slug: "kore-caja-gelatinas-x8",
    name: "Kore Caja x8",
    tagline: "Caja de 8 barras para tu plan de entrenamiento mensual",
    description:
      "Caja con 8 barras de gelatina de remolacha bioactivada para cubrir tu plan de entrenamiento mensual. Incluye combinación de 10K y 21K para variar según la intensidad de cada sesión. La forma más deliciosa de mejorar tu rendimiento.",
    price: 89_900,
    originalPrice: 103_200,
    image: "/productos/caja-gelatinas.jpg",
    badge: "Popular",
    rating: 4.9,
    reviews: 567,
    benefits: [
      "Plan mensual de nitratos completo",
      "Mix de gelatinas 10K y 21K",
      "Ahorra un 12% vs. compra individual",
      "Envío gratis incluido",
    ],
    ingredients: [],
    category: "Packs",
  },
  {
    slug: "kore-pack-carrera",
    name: "Kore Pack Carrera",
    tagline: "Todo lo que necesitas para tu próxima carrera",
    description:
      "Pack completo con el protocolo de nitratos para tu carrera: gelatinas de carga y refuerzo, más una guía de uso para optimizar la absorción. Incluye 4 gelatinas 10K y 2 jugos naturales para la semana previa.",
    price: 69_900,
    originalPrice: 85_400,
    image: "/productos/pack-carrera.jpg",
    badge: "Mejor valor",
    rating: 4.9,
    reviews: 412,
    benefits: [
      "Protocolo completo de nitratos pre-carrera",
      "Ahorra un 18% vs. compra individual",
      "Guía de carga de nitratos incluida",
      "Envío prioritario gratis",
    ],
    ingredients: [],
    category: "Packs",
  },
  {
    slug: "kore-discovery-pack",
    name: "Kore Discovery Pack",
    tagline: "Conoce todos nuestros productos por primera vez",
    description:
      "¿Primera vez con Kore? Este pack es para ti. Incluye 2 gelatinas 10K, 1 gelatina 21K y 1 jugo natural para que pruebes todo y descubras cómo los nitratos de remolacha pueden transformar tu rendimiento.",
    price: 49_900,
    image: "/productos/discovery.jpg",
    badge: "Nuevo",
    rating: 4.7,
    reviews: 234,
    benefits: [
      "Prueba todos los productos Kore",
      "Ideal para tu primera experiencia",
      "Incluye guía de protocolo de carga",
      "Precio especial de introducción",
    ],
    ingredients: [],
    category: "Packs",
  },
];

// ─── Testimonials ───────────────────────────────────────────────────
export const testimonials: Testimonial[] = [
  {
    name: "Andrés Lopera",
    age: 34,
    location: "Barranquilla",
    text: "Desde que uso Kore antes de mis carreras, mis tiempos en 10K mejoraron notablemente. Se siente la diferencia en la oxigenación, especialmente en los últimos kilómetros.",
    product: "Kore Gelatina 10K",
    rating: 5,
  },
  {
    name: "Valentina Ríos",
    age: 28,
    location: "Bogotá",
    text: "Me encanta el formato barra, es super práctico para llevar en el bolsillo del short. Además el sabor es increíble, no parece un suplemento.",
    product: "Kore Gelatina 10K",
    rating: 5,
  },
  {
    name: "Diego Morales",
    age: 41,
    location: "Cali",
    text: "Corrí mi primera media maratón con la Gelatina 21K y fue impresionante. Mantuve un ritmo constante sin esa fatiga que sentía en entrenamientos previos. Totalmente recomendado.",
    product: "Kore Gelatina 21K",
    rating: 5,
  },
  {
    name: "Camila Herrera",
    age: 31,
    location: "Cartagena",
    text: "Compré la caja de 8 para el mes y no he vuelto a entrenar sin Kore. Mis compañeros de running ya todos están pidiendo la suya. Es adictivo lo bien que te sientes.",
    product: "Kore Caja x8",
    rating: 4,
  },
];
